site_name: OpenGL MSAT
theme:
  name: 'material'
nav:
  - Home: index.md
  - Getting started: getting-started/getting-started.md
  - Controls:
    - Keyboard: controls/keyboard.md
    - Key enum: controls/key-enum.md