site_name: OpenGL MSAT
theme:
  name: 'material'
nav:
  - Home: index.md
  - Getting started:
    - Getting started: getting-started/getting-started.md
    - Public header: getting-started/public-header.md
    - Window: window/window.md
    - First app: getting-started/first-app.md
    - Shader builders: getting-started/shader-builders.md
    - Vectors and matrices: getting-started/vectors-matrices.md
    - Going 3D: getting-started/going-3d.md
    - Custom shaders: getting-started/custom-shaders.md
    - Debugging: getting-started/debugging.md
  - Vertices:
    - VAO: vertex/vao.md
    - VBO: vertex/vbo.md
    - Vertex attributes: vertex/vertex-attribute.md
  - Shaders:
    - Shaders: shader/shader.md
    - Vertex shader builder: shader/vertex-shader-builder.md
    - Fragment shader builder: shader/fragment-shader-builder.md
  - Rendering:
    - Rendering: render/render.md
    - Settings: render/render-settings.md
    - State: render/render-state.md
  - Camera:
    - Camera: camera/camera.md
    - Projections: lists/projections.md
  - Controls:
    - Keyboard: controls/keyboard.md
    - Key enum: controls/key-enum.md
  - Binding and context:
    - Context: context/context.md
    - Bindable: context/bindable.md
    - Bindable classes: lists/bindable-classes.md
  - Misc.:
    - Timer: timer/timer.md
  - Debugging:
    - System info: tools/sysinfo.md
  - Enumerations:
    - Projections: lists/projections.md
    - Shader stages: lists/shader-stage.md
    - Vertex attributes: vertex/vertex-attribute.md
    - Keys: controls/key-enum.md
    - Projections: lists/render-options.md
  - Troubleshooting: troubleshooting.md
  - Roadmap: roadmap.md