site_name: OpenGL MSAT
theme:
  name: 'material'
nav:
  - Home: index.md
  - Getting started:
    - Getting started: getting-started/getting-started.md
    - Window: window/window.md
    - VAO: vertex/vao.md
    - VBO: vertex/vbo.md
  - Shaders:
      - Shaders: shader/shader.md
  - Rendering:
    - Rendering: render/render.md
    - Settings: render/render-settings.md
  - Controls:
    - Keyboard: controls/keyboard.md
    - Key enum: controls/key-enum.md
  - Misc.:
    - Context: context/context.md
    - Bindable classes: lists/bindable-classes.md
    - Timer: timer/timer.md
  - Troubleshooting: troubleshooting.md
  - Roadmap: roadmap.md