site_name: OpenGL MSAT
theme:
  name: 'material'
nav:
  - Home: index.md
  - Getting started:
    - Getting started: getting-started/getting-started.md
    - Public header: getting-started/public-header.md
    - Window: window/window.md
    - First app: getting-started/first-app.md
    - Shader builders: getting-started/shader-builders.md
    - Vectors and matrices: getting-started/vectors-matrices.md
    - Going 3D: getting-started/going-3d.md
    - Custom shaders: getting-started/custom-shaders.md
  - Guides:
    - Texturing and materials: getting-started/texturing.md
    - Adding lights: getting-started/lights.md
    - Basic animations: getting-started/animations.md
    - Managing a scene: getting-started/manage-scene.md
    - Normal mapping: getting-started/normal-mapping.md
    - Create picture-in-picture: getting-started/pip.md
    - Creating a UI: getting-started/ui.md
  - Concepts:
      - Vertices:
          - VAO: vertex/vao.md
          - VBO: vertex/vbo.md
          - Vertex attributes: vertex/vertex-attribute.md
          - VBO-managed scene: vertex/vbo-scene.md
      - Geometry:
          - Cube: geometry/cube.md
          - Shapes: geometry/shapes.md
          - ObjectXD: geometry/object-xd.md
          - Object collection: geometry/object-collection.md
      - Shaders:
          - Shaders: shader/shader.md
          - Uniform values: shader/uniform.md
          - Vertex shader builder: shader/vertex-shader-builder.md
          - Fragment shader builder: shader/fragment-shader-builder.md
      - Camera and projection:
          - Camera: camera/camera.md
          - Projections: camera/projections.md
      - Lights:
        - Light basics: lights/lights.md
        - Directional light: lights/directional.md
        - Point light: lights/point-light.md
        - Spot light: lights/spot-light.md
        - Normal mapping: lights/normal-mapping.md
      - Textures:
        - Texture basics: textures/textures.md
        - Texture options: textures/texture-options.md
        - 2D textures: textures/texture-2d.md
        - Materials: textures/materials.md
        - Texture unit manager: textures/tum.md
        - Cubemaps: textures/cubemaps.md
        - Skybox: textures/skybox.md
      - Controls:
        - Keyboard: controls/keyboard.md
        - Key enum: controls/key-enum.md
      - Animation:
        - Animation basics: animation/animation.md
        - Blueprints: animation/blueprint.md
        - Control: animation/control.md
        - Iterations: animation/iterations.md
        - Timing functions: animation/timing-functions.md
      - Framebuffers:
        - Framebuffer basics: fbo/fbo.md
        - Framebuffer manager: fbo/fbo-mng.md
        - Attachments: fbo/attachments.md
        - Depth mapping: fbo/depth-mapping.md
        - Screen quad: fbo/screen-quad.md
        - Screen quad effects: fbo/screen-quad-fx.md
      - UI:
        - UI basics: ui/ui.md
        - UI elements: ui/ui-elements.md
        - Components:
          - Progress bar: ui/progress-bar.md
  - Rendering:
    - Rendering: render/render.md
    - Settings: render/render-settings.md
    - State: render/render-state.md
    - Scene management: render/scene-management.md
    - VBO-managed scene: vertex/vbo-scene.md
    - Buffer clearing: render/buffer-clearing.md
  - Misc.:
    - Timer: misc/timer.md
    - Math: misc/math.md
    - Types:
      - Color: misc/color.md
      - Image: misc/image.md
    - Binding and context:
      - Context: context/context.md
      - Bindable: context/bindable.md
      - Bindable classes: lists/bindable-classes.md
  - Debugging:
    - System info: tools/sysinfo.md
    - Messaging: tools/messaging.md
    - Helper: tools/helper.md
    - Grid: tools/grid.md
    - Dump: tools/dump.md
  - Enumerations:
    - Projections: lists/projections.md
    - Shader stages: lists/shader-stage.md
    - Vertex attributes: vertex/vertex-attribute.md
    - Keys: controls/key-enum.md
    - Render options: lists/render-options.md
    - Framebuffers: lists/framebuffer-enums.md
    - Animations: lists/animation-enums.md
    - Textures: lists/texture-enums.md
  - Troubleshooting: troubleshooting.md