site_name: OpenGL MSAT
theme:
  name: 'material'
nav:
  - Home: index.md
  - Getting started:
    - Getting started: getting-started/getting-started.md
    - Window: window/window.md
  - Controls:
    - Keyboard: controls/keyboard.md
    - Key enum: controls/key-enum.md
  - Misc.:
    - Context: context/context.md
    - Bindable classes: lists/bindable-classes.md
    - Timer: timer/timer.md